import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {handle} from '../server/api.mjs';
import {close} from '../server/db.mjs';
async function call(path,method='GET',payload,cookie=''){let bytes=payload?Buffer.from(JSON.stringify(payload)):Buffer.alloc(0),req=Readable.from(bytes.length?[bytes]:[]);req.url='/api'+path;req.method=method;req.headers={cookie,host:'localhost:8787'};let status,headers,result='';await handle(req,{writeHead(s,h){status=s;headers=h},end(x){result+=x||''}});return {status,headers,body:JSON.parse(result)}}
test('owner bulk import creates linked accounts and stock exactly once',async()=>{let dir=await mkdtemp(join(tmpdir(),'star-bulk-'));process.env.STAR_MART_DATA_DIR=dir;try{await call('/setup','POST',{name:'Owner',password:'secret123'});let owner=(await call('/login','POST',{password:'secret123'})).headers['set-cookie'].split(';')[0];let payload={customers:[{name:'Ayesha',email:'ayesha@example.com',phone:'03001234567',temporary_password:'secret123'}],products:[{sku:'RICE-1',barcode:'12345',name:'Rice',category:'Rice & Grains',price_rs:'300',cost_rs:'200',opening_stock:'10',reorder_level:'2'}]};assert.equal((await call('/bulk/import','POST',payload)).status,401);let first=await call('/bulk/import','POST',payload,owner);assert.equal(first.status,200,JSON.stringify(first.body));assert.equal(first.body.customersAdded,1);assert.equal(first.body.productsAdded,1);let again=await call('/bulk/import','POST',payload,owner);assert.equal(again.body.customersSkipped,1);assert.equal(again.body.productsSkipped,1);let state=await call('/state','GET',null,owner);assert.equal(Number(state.body.products[0].stock_milli),10000);let customers=await call('/customers','GET',null,owner);assert.equal(customers.body.customers.length,1);assert.equal((await call('/customer/login','POST',{email:'ayesha@example.com',password:'secret123'})).status,200);let conflict=await call('/bulk/import','POST',{products:[{...payload.products[0],sku:'OTHER'}]},owner);assert.equal(conflict.status,400);assert.equal((await call('/state','GET',null,owner)).body.products.length,1)}finally{await close();await rm(dir,{recursive:true,force:true})}});
