import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {handle} from '../server/api.mjs';
import {close} from '../server/db.mjs';
import {allocate,lineAmount,paisa,milli} from '../server/money.mjs';
async function request(path,method='GET',payload,cookie='',origin=''){let raw=payload?JSON.stringify(payload):'',req=Readable.from(raw?[Buffer.from(raw)]:[]);req.url='/api'+path;req.method=method;req.headers={cookie,host:'localhost:8787',origin};let status,headers,output='';let res={writeHead(s,h){status=s;headers=h},end(x){output+=x||''}};await handle(req,res);return {status,headers,body:JSON.parse(output)}}
test('fixed amounts and allocation preserve exact totals',()=>{assert.equal(paisa('10.01'),1001);assert.equal(milli('0.125'),125);assert.equal(lineAmount(125,1001),125);assert.deepEqual(allocate(1,[1,1]),[1,0]);assert.throws(()=>paisa('1.001'))});
test('store operations preserve stock, receipt totals and rollback',async()=>{let dir=await mkdtemp(join(tmpdir(),'star-mart-'));process.env.STAR_MART_DATA_DIR=dir;try{let r=await request('/setup','POST',{name:'Owner',password:'correct-horse-battery'});assert.equal(r.status,201,JSON.stringify(r.body));r=await request('/login','POST',{password:'correct-horse-battery'});assert.equal(r.status,200,JSON.stringify(r.body));let cookie=r.headers['set-cookie'].split(';')[0];let call=(p,m='GET',v)=>request(p,m,v,cookie);r=await call('/products','POST',{name:'Milk',sku:'MILK-1',barcode:'1234567890123',opening:2,cost:'80.25',price:'100.50',reorder:4,reorderQty:12});assert.equal(r.status,201,JSON.stringify(r.body));let productId=r.body.id;let publicBefore=await request('/public/products');assert.equal(publicBefore.status,200);assert.equal(publicBefore.body.products[0].name,'Milk');assert.equal(Number(publicBefore.body.products[0].stock_milli),2000);r=await call('/purchases','POST',{productId,qty:10,cost:'82.00',batch:'B-01',expiry:'2027-01-01',payment:'Unpaid'});assert.equal(r.status,201,JSON.stringify(r.body));r=await call('/checkout','POST',{lines:[{productId,qty:3}],discount:'1.01',tax:'0.50',payment:'Cash',received:'301.00',customer:'Walk-in'});assert.equal(r.status,201,JSON.stringify(r.body));assert.equal(r.body.subtotal,30150);assert.equal(r.body.total,30099);assert.equal(r.body.lines.reduce((n,x)=>n+x.total,0),r.body.total);r=await call('/adjustments','POST',{productId,change:-1,reason:'Damaged',note:'Dropped'});assert.equal(r.status,201,JSON.stringify(r.body));r=await call('/expenses','POST',{category:'Rent',description:'Shop rent',amount:'1500.25'});assert.equal(r.status,201);r=await call('/state');assert.equal(Number(r.body.products[0].stock_milli),8000);let publicAfter=await request('/public/products');assert.equal(Number(publicAfter.body.products[0].stock_milli),8000);assert.equal(publicAfter.body.products[0].price_paisa,10050);assert.equal(r.body.sales.length,1);assert.equal(r.body.receipts.length,1);assert.equal(r.body.expenses.length,1);r=await call('/checkout','POST',{lines:[{productId,qty:9}],payment:'Cash'});assert.equal(r.status,400);r=await call('/state');assert.equal(Number(r.body.products[0].stock_milli),8000);assert.equal(r.body.receipts.length,1);r=await call('/products','POST',{name:'Duplicate barcode',barcode:'1234567890123'});assert.equal(r.status,409)}finally{await close();await rm(dir,{recursive:true,force:true})}});
test('legacy backup import preserves detail and calculated stock',async()=>{let dir=await mkdtemp(join(tmpdir(),'star-mart-import-'));process.env.STAR_MART_DATA_DIR=dir;try{await request('/setup','POST',{name:'Owner',password:'correct-horse-battery'});let r=await request('/login','POST',{password:'correct-horse-battery'}),cookie=r.headers['set-cookie'].split(';')[0],call=(p,m='GET',v)=>request(p,m,v,cookie);let old={version:1,products:[{id:'p1',name:'Tea',sku:'T-1',barcode:'999999',category:'Grocery',opening:2,cost:150,price:200,reorder:5,brand:'A',location:'A1'}],vendors:[{id:'v1',name:'Supplier',phone:'123'}],purchases:[{id:'b1',productId:'p1',vendorId:'v1',qty:10,cost:155,batch:'LOT',expiry:'2027-04-01',payment:'Paid'}],sales:[{id:'s1',productId:'p1',qty:3,price:200,receipt:'OLD-1',payment:'Cash',costAtSale:155}],adjustments:[{id:'a1',productId:'p1',change:-1,reason:'Damaged',note:'Broken'}],expenses:[{id:'e1',category:'Rent',description:'Monthly',amount:2500}]};r=await call('/import-legacy','POST',old);assert.equal(r.status,201,JSON.stringify(r.body));r=await call('/state');assert.equal(Number(r.body.products[0].stock_milli),8000);assert.equal(r.body.products[0].barcode,'999999');assert.equal(r.body.purchases[0].batch,'LOT');assert.equal(r.body.receipts[0].total_paisa,60000);assert.equal(r.body.expenses.length,1);let duplicate=await call('/import-legacy','POST',old);assert.notEqual(duplicate.status,201)}finally{await close();await rm(dir,{recursive:true,force:true})}});

test('local Vite proxy accepts setup origin while cross-site origins remain blocked',async()=>{let dir=await mkdtemp(join(tmpdir(),'star-mart-origin-'));process.env.STAR_MART_DATA_DIR=dir;try{let ok=await request('/setup','POST',{name:'Hassan',password:'correct-horse-battery'},'','http://localhost:5173');assert.equal(ok.status,201,JSON.stringify(ok.body));let bad=await request('/login','POST',{password:'correct-horse-battery'},'','https://evil.example');assert.equal(bad.status,403)}finally{await close();await rm(dir,{recursive:true,force:true})}});
