import {tx} from './db.mjs';
import {id,passwordHash} from './auth.mjs';
import {paisa,wholeQuantity as milli} from './money.mjs';
const fail=message=>Object.assign(new Error(message),{status:400});
const clean=(v,max=250)=>String(v??'').trim().slice(0,max);
const categories=new Set(['Fruits','Vegetables','Dairy & Eggs','Bakery','Meat & Poultry','Fish & Seafood','Rice & Grains','Flour & Baking','Pulses & Lentils','Cooking Oil & Ghee','Spices & Condiments','Tea & Coffee','Beverages','Snacks & Sweets','Frozen Foods','Canned & Packaged','Personal Care','Household Cleaning','Baby Care','Pet Supplies','Other']);
const number=(v,label)=>{let n=Number(v||0);if(!Number.isFinite(n)||n<0)throw fail(label+' must be zero or more');return n};
export async function importCatalogBatch(payload){
  let customers=payload.customers||[],products=payload.products||[];
  if(!Array.isArray(customers)||!Array.isArray(products)||customers.length+products.length===0||customers.length+products.length>80)throw fail('Each import batch needs 1–80 rows');
  return tx(async c=>{
    let result={customersAdded:0,customersSkipped:0,productsAdded:0,productsSkipped:0,products:[]};
    for(const row of customers){let email=clean(row.email,250).toLowerCase(),name=clean(row.name),phone=clean(row.phone,30),password=String(row.temporary_password||'');if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw fail('Customer needs a name and valid email');let prior=await c.query('SELECT id FROM customer_accounts WHERE email=$1',[email]);if(prior.rows.length){result.customersSkipped++;continue}if(password.length<8||password.length>128)throw fail('Temporary password needs 8–128 characters for '+email);let salt=id();await c.query('INSERT INTO customer_accounts(id,name,email,phone,password_hash,salt) VALUES($1,$2,$3,$4,$5,$6)',[id(),name,email,phone,passwordHash(password,salt),salt]);result.customersAdded++}
    for(const row of products){let sku=clean(row.sku,80)||null,barcode=clean(row.barcode,80)||null,name=clean(row.name),category=clean(row.category),unit=clean(row.unit)||'piece',price=paisa(number(row.price_rs,'Price'),'Price'),cost=paisa(number(row.cost_rs,'Cost'),'Cost'),opening=milli(number(row.opening_stock,'Opening stock'),'Opening stock'),reorder=milli(number(row.reorder_level,'Reorder level'),'Reorder level');if(!name||!sku)throw fail('Every product needs a name and SKU');if(category&&!categories.has(category))throw fail('Unknown grocery category for '+sku);let match=await c.query('SELECT id,sku FROM products WHERE sku=$1 OR ($2::text IS NOT NULL AND barcode=$2)',[sku,barcode]);if(match.rows.length){if(match.rows.length>1||match.rows[0].sku!==sku)throw fail('SKU/barcode conflict for '+sku);result.productsSkipped++;result.products.push({sku,id:match.rows[0].id,added:false});continue}let key=id();await c.query('INSERT INTO products(id,name,sku,barcode,brand,category,pack_size,unit,location,cost_paisa,price_paisa,reorder_milli,image,description) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)',[key,name,sku,barcode,clean(row.brand),category,clean(row.pack_size),unit,clean(row.location),cost,price,reorder,'',clean(row.description,3000)]);if(opening)await c.query("INSERT INTO stock_movements(id,product_id,qty_milli,kind,reason) VALUES($1,$2,$3,'opening','Bulk import opening stock')",[id(),key,opening]);result.productsAdded++;result.products.push({sku,id:key,added:true})}
    return result;
  });
}
