import {Pool} from 'pg';
let pool,local;
export async function db(){if(process.env.DATABASE_URL){pool ||= new Pool({connectionString:process.env.DATABASE_URL,max:process.env.VERCEL?1:5});return pool}if(process.env.VERCEL)throw Error('DATABASE_URL is required on Vercel. Connect a Postgres database.');if(!local){const {PGlite}=await import('@electric-sql/pglite');local=new PGlite(process.env.STAR_MART_DATA_DIR||'./.data')}return local}
export async function tx(fn){const database=await db();if(database.connect){const c=await database.connect();try{await c.query('BEGIN');let value=await fn(c);await c.query('COMMIT');return value}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}await database.query('BEGIN');try{let value=await fn(database);await database.query('COMMIT');return value}catch(e){await database.query('ROLLBACK');throw e}}
let initialized;
export function init(){initialized ||= (async()=>{const d=await db();for (const statement of `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, password_hash TEXT NOT NULL, salt TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS admin_identities (uid TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS vendors (id TEXT PRIMARY KEY,name TEXT NOT NULL,contact TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL DEFAULT '',email TEXT NOT NULL DEFAULT '',address TEXT NOT NULL DEFAULT '',terms TEXT NOT NULL DEFAULT '',tax_id TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY,name TEXT NOT NULL,sku TEXT UNIQUE,barcode TEXT UNIQUE,brand TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT '',pack_size TEXT NOT NULL DEFAULT '',unit TEXT NOT NULL DEFAULT 'piece',location TEXT NOT NULL DEFAULT '',vendor_id TEXT REFERENCES vendors(id) ON DELETE SET NULL,cost_paisa BIGINT NOT NULL DEFAULT 0 CHECK(cost_paisa>=0),price_paisa BIGINT NOT NULL DEFAULT 0 CHECK(price_paisa>=0),reorder_milli BIGINT NOT NULL DEFAULT 0 CHECK(reorder_milli>=0),reorder_qty_milli BIGINT NOT NULL DEFAULT 0 CHECK(reorder_qty_milli>=0),tax_rate_bps INTEGER NOT NULL DEFAULT 0,image TEXT NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS stock_movements (id TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),qty_milli BIGINT NOT NULL CHECK(qty_milli<>0),kind TEXT NOT NULL CHECK(kind IN ('opening','purchase','sale','adjustment')),ref_id TEXT,reason TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',batch TEXT NOT NULL DEFAULT '',expiry DATE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_movements_product ON stock_movements(product_id);
CREATE TABLE IF NOT EXISTS purchases (id TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),vendor_id TEXT REFERENCES vendors(id) ON DELETE SET NULL,qty_milli BIGINT NOT NULL CHECK(qty_milli>0),unit_cost_paisa BIGINT NOT NULL CHECK(unit_cost_paisa>=0),invoice TEXT NOT NULL DEFAULT '',payment TEXT NOT NULL DEFAULT 'Paid',batch TEXT NOT NULL DEFAULT '',expiry DATE,note TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sales (id TEXT PRIMARY KEY,receipt TEXT NOT NULL,product_id TEXT NOT NULL REFERENCES products(id),qty_milli BIGINT NOT NULL CHECK(qty_milli>0),unit_price_paisa BIGINT NOT NULL CHECK(unit_price_paisa>=0),line_total_paisa BIGINT NOT NULL CHECK(line_total_paisa>=0),cost_at_sale_paisa BIGINT NOT NULL CHECK(cost_at_sale_paisa>=0),payment TEXT NOT NULL,customer TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_sales_receipt ON sales(receipt);
CREATE TABLE IF NOT EXISTS receipts (id TEXT PRIMARY KEY,subtotal_paisa BIGINT NOT NULL,discount_paisa BIGINT NOT NULL,tax_paisa BIGINT NOT NULL,total_paisa BIGINT NOT NULL,received_paisa BIGINT NOT NULL,payment TEXT NOT NULL,customer TEXT NOT NULL,note TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS adjustments (id TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),qty_milli BIGINT NOT NULL CHECK(qty_milli<>0),reason TEXT NOT NULL,note TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS expenses (id TEXT PRIMARY KEY,category TEXT NOT NULL,description TEXT NOT NULL,amount_paisa BIGINT NOT NULL CHECK(amount_paisa>0),payment TEXT NOT NULL,reference TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS customer_orders (id TEXT PRIMARY KEY,customer_uid TEXT NOT NULL,customer_name TEXT NOT NULL,customer_email TEXT NOT NULL DEFAULT '',customer_phone TEXT NOT NULL DEFAULT '',fulfillment TEXT NOT NULL CHECK(fulfillment IN ('Pickup','Delivery')),address TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'Pending' CHECK(status IN ('Pending','Fulfilled','Cancelled')),total_paisa BIGINT NOT NULL CHECK(total_paisa>=0),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS customer_order_items (id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES customer_orders(id),product_id TEXT NOT NULL REFERENCES products(id),name TEXT NOT NULL,qty_milli BIGINT NOT NULL CHECK(qty_milli>0),unit_price_paisa BIGINT NOT NULL CHECK(unit_price_paisa>=0),line_total_paisa BIGINT NOT NULL CHECK(line_total_paisa>=0));
CREATE INDEX IF NOT EXISTS idx_order_items_product ON customer_order_items(product_id);
CREATE TABLE IF NOT EXISTS store_accounts (id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,salt TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('staff','vendor')),vendor_id TEXT REFERENCES vendors(id),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS account_sessions (token_hash TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES store_accounts(id),expires_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS customer_accounts (id TEXT PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,phone TEXT NOT NULL DEFAULT '',password_hash TEXT NOT NULL,salt TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS customer_sessions (token_hash TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customer_accounts(id),expires_at TIMESTAMPTZ NOT NULL);
CREATE TABLE IF NOT EXISTS customer_credit_payments (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customer_accounts(id),receipt_id TEXT NOT NULL REFERENCES receipts(id),amount_paisa BIGINT NOT NULL CHECK(amount_paisa>0),method TEXT NOT NULL,reference TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS loyalty_entries (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customer_accounts(id),receipt_id TEXT NOT NULL REFERENCES receipts(id),points INTEGER NOT NULL CHECK(points<>0),kind TEXT NOT NULL CHECK(kind IN ('earned','redeemed')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS vendor_applications (id TEXT PRIMARY KEY,business TEXT NOT NULL,contact TEXT NOT NULL,email TEXT NOT NULL,phone TEXT NOT NULL,address TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'Pending' CHECK(status IN ('Pending','Approved','Rejected')),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS vendor_payments (id TEXT PRIMARY KEY,vendor_id TEXT NOT NULL REFERENCES vendors(id),amount_paisa BIGINT NOT NULL CHECK(amount_paisa>0),method TEXT NOT NULL CHECK(method IN ('Cash','Bank transfer','Card')),reference TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS product_images (product_id TEXT PRIMARY KEY REFERENCES products(id) ON DELETE CASCADE,data BYTEA NOT NULL,mime TEXT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());`.split(';').map(x=>x.trim()).filter(Boolean)) await d.query(statement);await d.query('ALTER TABLE purchases ADD COLUMN IF NOT EXISTS paid_paisa BIGINT NOT NULL DEFAULT 0');await d.query('ALTER TABLE receipts ADD COLUMN IF NOT EXISTS customer_id TEXT');await d.query('CREATE INDEX IF NOT EXISTS idx_receipts_customer ON receipts(customer_id,created_at)');})();return initialized}
export async function close(){if(pool)await pool.end();if(local)await local.close();pool=null;local=null;initialized=null}
