import React,{useEffect,useState,useRef} from 'react';
import {Eye,EyeOff,Archive,Trash2,Search,MoreHorizontal,ChevronDown,X,CheckCircle2} from 'lucide-react';
const money=n=>'Rs '+(Number(n||0)/100).toLocaleString('en-PK',{maximumFractionDigits:2});
const actions=[['hide','Hide from website',EyeOff],['show','Show / restore',Eye],['archive','Archive product',Archive],['delete','Delete permanently',Trash2]];
export default function AdminCatalog({products,vendors,onEdit,onImage,onRefresh,stock}){
 let [selected,setSelected]=useState([]),[vendor,setVendor]=useState('all'),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[menu,setMenu]=useState(null),[dialog,setDialog]=useState(null);let cancel=useRef(),trigger=useRef();
 let shown=products.filter(p=>(vendor==='all'||(vendor==='none'?!p.vendor_id:p.vendor_id===vendor))&&(status==='all'||(p.catalog_status||'active')===status)&&(p.name+' '+p.sku+' '+p.barcode+' '+p.brand).toLowerCase().includes(search.toLowerCase())),selectable=shown.slice(0,500),all=selectable.length>0&&selectable.every(p=>selected.includes(p.id));
 useEffect(()=>{setSelected([]);setMenu(null)},[vendor,search,status]);useEffect(()=>setSelected(ids=>ids.filter(id=>products.some(p=>p.id===id))),[products]);
 useEffect(()=>{if(!menu)return;let close=e=>{if(!e.target.closest('.ac-menu-wrap'))setMenu(null)},key=e=>{if(e.key==='Escape')setMenu(null)};document.addEventListener('click',close);document.addEventListener('keydown',key);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',key)}},[menu]);
 useEffect(()=>{if(!dialog)return;cancel.current?.focus();let key=e=>{if(e.key==='Escape'&&!busy)setDialog(null);if(e.key==='Tab'){let modal=cancel.current?.closest('[role="dialog"]'),nodes=modal?.querySelectorAll('button:not(:disabled)'),first=nodes?.[0],last=nodes?.[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);trigger.current?.focus()}},[dialog,busy]);
 function toggle(id){setSelected(ids=>ids.includes(id)?ids.filter(x=>x!==id):ids.length<500?[...ids,id]:ids)}
 function deleteVendorProducts(event){let ids=products.filter(p=>vendor==='none'?!p.vendor_id:p.vendor_id===vendor).map(p=>p.id);setError('');trigger.current=event.currentTarget;setDialog({type:'delete',ids,name:(vendor==='none'?'Unassigned':vendors.find(v=>v.id===vendor)?.name||'Selected vendor')+' — '+ids.length+' products'})}
 function choose(type,ids,event){setMenu(null);trigger.current=event.currentTarget.closest(".ac-menu-wrap")?.querySelector("button");let name=ids.length===1?products.find(p=>p.id===ids[0])?.name:ids.length+' selected products';if(type==='hide'||type==='show'){apply(type,ids);return}setDialog({type,ids,name})}
 async function apply(type,ids){setBusy(true);setError('');setMessage('');try{let totalChanged=0,totalSkipped=[];for(let start=0;start<ids.length;start+=500){let r=await fetch('/api/products/bulk-action',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({action:type,ids:ids.slice(start,start+500)})}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not update these products');totalChanged+=Number(j.changed||0);totalSkipped.push(...(j.skipped||[]))}let j={changed:totalChanged,skipped:totalSkipped};await onRefresh();setSelected([]);setDialog(null);let label={hide:'hidden from website',show:'shown on website',archive:'archived',delete:'deleted'}[type];setMessage(j.changed+' '+(j.changed===1?'product':'products')+' '+label+'.'+(j.skipped?.length?' '+j.skipped.length+' retained because purchase, stock or order history exists. You can archive them instead.':''))}catch(e){setError(e.message)}finally{setBusy(false)}}
 function options(ids,product){let state=product?.catalog_status||'active';return <div className="ac-dropdown" role="menu" aria-label="Product actions">{actions.filter(([type])=>!product||(type==='hide'?state==='active':type==='show'?state!=='active':type==='archive'?state!=='archived':true)).map(([type,label,Icon])=><button role="menuitem" type="button" key={type} className={type==='delete'?'danger':''} disabled={busy} onClick={e=>choose(type,ids,e)}><Icon size={16}/><span>{label}</span></button>)}{product&&<label className="ac-photo" role="menuitem" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();e.currentTarget.querySelector("input")?.click()}}}><input type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={e=>{onImage?.(product.id,e.target.files?.[0]);e.target.value='';setMenu(null)}}/>Change photo</label>}</div>}
 return <section className="vp-card ac-catalog"><div className="vp-head"><div><h2>Product catalog</h2><p>Edit a product or open its ••• menu for more options.</p></div><span className="ac-count">{shown.length} products</span></div>
 <div className="vp-tools"><label><Search size={17}/><input aria-label="Search products" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a product…"/></label><select aria-label="Vendor" value={vendor} onChange={e=>setVendor(e.target.value)}><option value="all">All vendors</option><option value="none">No vendor assigned</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select aria-label="Product status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All products</option><option value="active">On website</option><option value="hidden">Hidden</option><option value="archived">Archived</option></select></div>
 <div className="ac-selection">{vendor!=='all'&&<button className="ac-vendor-delete" disabled={busy||!products.some(p=>vendor==='none'?!p.vendor_id:p.vendor_id===vendor)} onClick={deleteVendorProducts}><Trash2 size={15}/> Delete vendor products</button>}<label><input type="checkbox" disabled={busy} checked={all} onChange={e=>setSelected(e.target.checked?selectable.map(p=>p.id):[])}/> Select all shown</label>{selected.length>0?<><span>{selected.length} selected</span><div className="ac-menu-wrap"><button className="ac-manage" disabled={busy} aria-expanded={menu==='bulk'} aria-haspopup="menu" onClick={()=>setMenu(menu==='bulk'?null:'bulk')}>Actions for selected <ChevronDown size={15}/></button>{menu==='bulk'&&options(selected)}</div><button className="ac-clear" disabled={busy} onClick={()=>setSelected([])}>Clear</button></>:<small>Select products to manage several together.</small>}</div>
 {busy&&!dialog&&<p role="status">Updating products…</p>}{error&&<p className="vp-error" role="alert">{error}</p>}{message&&<div className="ac-success" role="status"><CheckCircle2 size={18}/><span>{message}</span><button aria-label="Dismiss message" onClick={()=>setMessage('')}><X size={16}/></button></div>}
 <div className="vp-table-wrap ac-table"><table><thead><tr>{['','Product','Vendor','SKU / barcode','Stock','Cost / price','Status','Actions'].map((x,i)=><th key={i}>{x}</th>)}</tr></thead><tbody>{shown.map(p=>{let state=p.catalog_status||'active';return <tr key={p.id} className={'ac-row ac-'+state}><td><input aria-label={'Select '+p.name} type="checkbox" disabled={busy} checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/></td><td><div className="vp-product ac-product">{p.image?<img src={p.image} alt=""/>:<span>▣</span>}<div><b>{p.name}</b><small>{p.category} · {p.pack_size||p.unit}</small></div></div></td><td>{vendors.find(v=>v.id===p.vendor_id)?.name||'Unassigned'}</td><td>{p.sku||'—'}<small>{p.barcode||'No barcode'}</small></td><td>{Number(stock(p))/1000} {p.unit}</td><td>{money(p.cost_paisa)} / {money(p.price_paisa)}</td><td><span className={'ac-status '+state}>{state==='active'?<Eye size={12}/>:state==='hidden'?<EyeOff size={12}/>:<Archive size={12}/>}{{active:'On website',hidden:'Hidden',archived:'Archived'}[state]}</span></td><td><div className="ac-row-actions"><button className="ac-edit" disabled={busy} onClick={()=>onEdit(p)}>Edit</button><div className="ac-menu-wrap"><button className="ac-more" disabled={busy} aria-label={'More options for '+p.name} aria-expanded={menu===p.id} aria-haspopup="menu" onClick={()=>setMenu(menu===p.id?null:p.id)}><MoreHorizontal size={20}/></button>{menu===p.id&&options([p.id],p)}</div></div></td></tr>})}</tbody></table></div>{!shown.length&&<div className="ac-empty">No products found. Try another vendor or search.</div>}
 {dialog&&<div className="ac-overlay" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)setDialog(null)}}><div className={'ac-dialog '+dialog.type} role="dialog" aria-modal="true" aria-labelledby="ac-title" aria-describedby="ac-description"><div className="ac-dialog-icon">{dialog.type==='delete'?<Trash2 size={25}/>:<Archive size={25}/>}</div><h2 id="ac-title">{dialog.type==='delete'?'Delete this selection?':'Archive this selection?'}</h2><strong className="ac-target">{dialog.name}</strong><p id="ac-description">{dialog.type==='delete'?'Permanent deletion cannot be undone. Products with any stock, purchase, sale or order history will be kept.':'These products will leave the website and stop appearing for new POS sales. Their stock and complete account history stay saved. You can restore them from this menu later.'}</p>{error&&<p className="vp-error">{error}</p>}<div className="ac-dialog-buttons"><button ref={cancel} disabled={busy} onClick={()=>setDialog(null)}>Keep products</button><button className="ac-confirm" disabled={busy} onClick={()=>apply(dialog.type,dialog.ids)}>{busy?'Please wait…':dialog.type==='delete'?'Yes, delete unused products':'Archive products'}</button></div></div></div>}
 </section>
}
