import React,{useEffect,useRef,useState} from 'react';
import {Search,Package,UserRound,CheckCircle2,Mail,Phone,ShieldCheck,ChevronLeft,ChevronRight} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Button} from '@/components/ui/button';
export const money=n=>'Rs '+(Number(n||0)/100).toLocaleString('en-PK',{maximumFractionDigits:2});
export const when=x=>new Date(x).toLocaleString('en-PK',{timeZone:'Asia/Karachi',dateStyle:'medium',timeStyle:'short'});
const quantity=n=>Math.round(Number(n||0)/1000).toLocaleString('en-PK');
async function request(path,method='GET',body){let r=await fetch('/api'+path,{method,credentials:'same-origin',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not complete this action');return j}
export function WorkspaceTabs({value,onChange,items,label='Workspace sections'}){return <Tabs value={value} onValueChange={onChange} className="aw-tabs"><TabsList aria-label={label}>{items.map(([key,name,count])=><TabsTrigger key={key} value={key}>{name}{count!==undefined&&<span>{count}</span>}</TabsTrigger>)}</TabsList></Tabs>}
export function Summary({items}){return <div className="aw-summary">{items.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>}
function textOf(node){if(node==null||typeof node==='boolean')return '';if(typeof node==='string'||typeof node==='number')return String(node);if(Array.isArray(node))return node.map(textOf).join(' ');return textOf(node.props?.children)}
export function RecordTable({title,columns,rows,search,setSearch,filter,setFilter,filters,placeholder='Search these records',empty='No records yet.'}){
 const [local,setLocal]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(20);let q=search??local,setQ=setSearch||setLocal;let shown=rows.filter(r=>textOf(r).toLowerCase().includes(q.toLowerCase())),pages=Math.max(1,Math.ceil(shown.length/size)),current=Math.min(page,pages),visible=shown.slice((current-1)*size,current*size);
 useEffect(()=>{setLocal('');setPage(1)},[title]);useEffect(()=>setPage(1),[q,filter,size]);
 return <section className="aw-records"><div className="aw-table-tools"><div><h2>{title}</h2><small>{shown.length} matching records</small></div><label className="aw-search"><Search size={17}/><input aria-label={'Search '+title} value={q} onChange={e=>setQ(e.target.value)} placeholder={placeholder}/>{q&&<button type="button" aria-label="Clear search" onClick={()=>setQ('')}>×</button>}</label>{setFilter&&<select aria-label="Record filter" value={filter} onChange={e=>setFilter(e.target.value)}>{filters.map(x=><option key={x} value={x}>{x==='all'?'All stock':x==='low'?'Low stock':'Available'}</option>)}</select>}</div><div className="aw-table-scroll"><table><thead><tr>{columns.map((c,i)=><th key={i}>{c}</th>)}</tr></thead><tbody>{visible.length?visible:<tr><td colSpan={columns.length}><div className="aw-empty"><Package size={28}/><p>{q?'No matches. Try another search.':empty}</p></div></td></tr>}</tbody></table></div><div className="aw-pagination"><span>{shown.length?`${(current-1)*size+1}–${Math.min(current*size,shown.length)} of ${shown.length}`:'0 records'}</span><label>Rows <select aria-label="Rows per page" value={size} onChange={e=>setSize(Number(e.target.value))}>{[10,20,50].map(n=><option key={n}>{n}</option>)}</select></label><Button variant="outline" aria-label="Previous page" disabled={current===1} onClick={()=>setPage(current-1)}><ChevronLeft size={16}/></Button><span>{current} / {pages}</span><Button variant="outline" aria-label="Next page" disabled={current>=pages} onClick={()=>setPage(current+1)}><ChevronRight size={16}/></Button></div></section>
}
export function OrdersWorkspace({orders,role,onAction,onPickup}){
 const [tab,setTab]=useState('pending'),[selected,setSelected]=useState(null),[cancel,setCancel]=useState(null),[reference,setReference]=useState(''),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');let filtered=orders.filter(o=>tab==='all'||tab==='pending'&&o.status==='Pending'||tab==='pickup'&&o.fulfillment==='Pickup'&&o.status==='Pending'||tab==='delivery'&&o.fulfillment==='Delivery'&&o.status==='Pending'||o.status.toLowerCase()===tab),order=orders.find(o=>o.id===selected),transfer=order?.payment_method?.includes('transfer');
 function open(o){setSelected(o.id);setError('');setReference('');setVerified(false)}
 async function perform(id,status){setBusy(true);setError('');try{let r=await onAction(id,status,status==='Fulfilled'?{paymentCollected:true,verifiedReference:reference.trim()}:{});if(!r)throw Error('Action could not be saved. Please check the message and try again.');setSelected(null);setCancel(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <><Summary items={[["Awaiting action",orders.filter(o=>o.status==='Pending').length],["Pickup",orders.filter(o=>o.status==='Pending'&&o.fulfillment==='Pickup').length],["Delivery",orders.filter(o=>o.status==='Pending'&&o.fulfillment==='Delivery').length],["Completed",orders.filter(o=>o.status==='Fulfilled').length]]}/><WorkspaceTabs value={tab} onChange={setTab} items={[['pending','Pending'],['pickup','Pickup'],['delivery','Delivery'],['fulfilled','Completed'],['cancelled','Cancelled'],['all','All orders']]}/><RecordTable title="Customer orders" columns={['Order / date','Customer','Items','Collection','Total','Status','Action']} rows={filtered.map(o=><tr key={o.id}><td><strong>{o.id}</strong><small>{when(o.created_at)}</small></td><td><strong>{o.customer_name}</strong><small>{o.customer_phone}</small></td><td>{o.items.length} product{o.items.length===1?'':'s'}</td><td>{o.fulfillment}<small>{o.payment_method}</small></td><td><strong>{money(o.total_paisa)}</strong></td><td><span className={'aw-status '+(o.status==='Pending'?'pending':'')}>{o.status}</span></td><td><Button variant="outline" onClick={()=>open(o)}>View details</Button></td></tr>)}/>
 <Dialog open={Boolean(order)&&!cancel} onOpenChange={v=>{if(!v&&!busy)setSelected(null)}}>{order&&<DialogContent className="aw-dialog"><DialogTitle>Order details</DialogTitle><DialogDescription>{order.id} · {when(order.created_at)}</DialogDescription><div className="aw-detail-grid"><div><small>Customer</small><strong>{order.customer_name}</strong><span>{order.customer_phone}</span><span>{order.customer_email||'No email'}</span></div><div><small>{order.fulfillment}</small><strong>{order.address||'Collect at store counter'}</strong><span>{order.payment_method} · {order.payment_status}</span></div></div><div className="aw-item-list">{order.items.map((i,n)=><div key={n}><span>{i.name}</span><b>× {quantity(i.qty_milli)}</b></div>)}</div><div className="aw-total"><span>Order total</span><strong>{money(order.total_paisa)}</strong></div>{order.payment_reference&&<p>Customer reference: <strong>{order.payment_reference}</strong></p>}{order.verified_reference&&<p>Verified reference: <strong>{order.verified_reference}</strong></p>}{order.status==='Pending'&&order.fulfillment==='Delivery'&&role==='admin'&&<form onSubmit={e=>{e.preventDefault();perform(order.id,'Fulfilled')}}><div className="aw-note">Close this order after the rider deposits the collected payment. Receipt, stock, sales and eligible points update together.</div>{transfer&&<label className="aw-field">Confirmed transaction reference<input required value={reference} onChange={e=>setReference(e.target.value)}/></label>}<label className="aw-check"><input type="checkbox" required checked={verified} onChange={e=>setVerified(e.target.checked)}/>I have received and verified {money(order.total_paisa)}.</label>{error&&<p className="aw-error" role="alert">{error}</p>}<Button className="primary" disabled={busy||!verified||transfer&&!reference.trim()}>{busy?'Saving…':'Payment received · Complete order'}</Button></form>}{order.status==='Pending'&&<div className="aw-actions">{order.fulfillment==='Pickup'&&<Button className="primary" onClick={()=>{setSelected(null);onPickup()}}>Collect payment at POS</Button>}<Button variant="outline" disabled={busy} onClick={()=>{setError('');setCancel(order)}}>Cancel order</Button></div>}</DialogContent>}</Dialog>
 <AlertDialog open={Boolean(cancel)} onOpenChange={v=>{if(!v&&!busy)setCancel(null)}}><AlertDialogContent className="aw-dialog"><AlertDialogTitle>Cancel this order?</AlertDialogTitle><AlertDialogDescription>{cancel?.customer_name} · {cancel?.id}. Reserved stock will be released. This does not delete past sales.</AlertDialogDescription>{error&&<p className="aw-error">{error}</p>}<div className="aw-actions"><AlertDialogCancel disabled={busy}>Keep order</AlertDialogCancel><Button className="primary" disabled={busy} onClick={()=>perform(cancel.id,'Cancelled')}>{busy?'Cancelling…':'Yes, cancel order'}</Button></div></AlertDialogContent></AlertDialog></>
}
export function CustomersWorkspace({customers,onPOS,renderCredit}){
 const [id,setId]=useState(''),[tab,setTab]=useState('details'),[info,setInfo]=useState(null),[error,setError]=useState('');const current=useRef(id);current.current=id;
 async function load(){let target=id;if(!target)return;try{let j=await request('/customers/'+encodeURIComponent(target)+'/overview');if(current.current===target){setInfo(j);setError('')}}catch(e){if(current.current===target)setError(e.message)}}
 useEffect(()=>{setInfo(null);setError('');setTab('details');load()},[id]);
 return <><Summary items={[["Customers",customers.length],["Total shopping",money(customers.reduce((n,c)=>n+Number(c.total_spend_paisa),0))],["Credit outstanding",money(customers.reduce((n,c)=>n+Number(c.outstanding_paisa),0))]]}/><div className="aw-toolbar"><strong><UserRound size={20}/>Customer workspace</strong><select aria-label="Select customer" value={id} onChange={e=>setId(e.target.value)}><option value="">Choose a customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.email}</option>)}</select>{info&&<Button className="primary" onClick={()=>onPOS(info.customer)}>Open POS for customer</Button>}</div>{error&&<p className="aw-error" role="alert">{error}</p>}
 {!id?<RecordTable title="Customer directory" columns={['Customer','Contact','Shopping','Credit due','Points','Action']} rows={customers.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email}<small>{c.phone||'No phone'}</small></td><td>{money(c.total_spend_paisa)}<small>{c.bill_count} bills</small></td><td>{money(c.outstanding_paisa)}</td><td>{c.points}</td><td><Button variant="outline" onClick={()=>setId(c.id)}>Open customer</Button></td></tr>)}/>:!info?<div className="aw-empty">{error?'Could not load customer details.':'Loading customer records…'}</div>:<><WorkspaceTabs value={tab} onChange={setTab} items={[['details','Details'],['bills','Shopping & bills'],['orders','Orders'],['credit','Credit & payments'],['points','Star points'],['monthly','Monthly totals']]}/>
 {tab==='details'&&<section className="aw-card"><h2>{info.customer.name}</h2><div className="aw-detail-grid"><div><small>Email</small><strong>{info.customer.email}</strong></div><div><small>Phone</small><strong>{info.customer.phone||'Not added'}</strong></div></div><Summary items={[["Shopping total",money(info.summary.totalSpendPaisa)],["Completed bills",info.summary.billCount],["Credit due",money(info.summary.outstandingPaisa)],["Star points",info.summary.points]]}/></section>}
 {tab==='bills'&&<RecordTable title="Customer shopping" columns={['Receipt / date','Items','Payment','Total','Due']} rows={info.bills.map(b=><tr key={b.id}><td>{b.id}<small>{when(b.createdAt)}</small></td><td>{b.items.map(i=>i.name+' × '+quantity(i.qtyMilli)).join(', ')}</td><td>{b.payment}</td><td>{money(b.totalPaisa)}</td><td>{money(b.duePaisa)}</td></tr>)}/>}
 {tab==='orders'&&<RecordTable title="Customer order history" columns={['Order / date','Collection','Status','Total','Receipt']} rows={info.orders.map(o=><tr key={o.id}><td>{o.id}<small>{when(o.created_at)}</small></td><td>{o.fulfillment}</td><td>{o.status}</td><td>{money(o.total_paisa)}</td><td>{o.receipt_id||'Pending sale'}</td></tr>)}/>}
 {tab==='credit'&&<><section className="aw-card"><h2>Collect outstanding credit</h2>{renderCredit(id,info,load)}</section><RecordTable title="Customer credit payments" columns={['Date','Receipt','Method','Amount']} rows={info.payments.map(p=><tr key={p.id}><td>{when(p.created_at)}</td><td>{p.receipt_id}</td><td>{p.method}</td><td>{money(p.amount_paisa)}</td></tr>)}/></>}
 {tab==='points'&&<><div className="aw-note">{info.summary.points} points available · {info.program.redemption}. Rewards apply only to eligible settled bills.</div><RecordTable title="Star points history" columns={['Date','Receipt','Activity','Points']} rows={info.pointsHistory.map(p=><tr key={p.id}><td>{when(p.created_at)}</td><td>{p.receipt_id||'—'}</td><td>{p.kind}</td><td>{p.points}</td></tr>)}/></>}
 {tab==='monthly'&&<RecordTable title="Monthly shopping totals" columns={['Month','Bills','Shopping total','Credit purchases']} rows={info.monthly.map(m=><tr key={m.month}><td>{m.month}</td><td>{m.bills}</td><td>{money(m.totalPaisa)}</td><td>{money(m.creditPaisa)}</td></tr>)}/>}</>}
 </>
}
export function TeamWorkspace({accounts,vendors,onCreate,onToggle}){
 const [tab,setTab]=useState('staff'),[form,setForm]=useState({}),[confirm,setConfirm]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(null);
 async function create(e){e.preventDefault();setBusy(true);setError('');try{let r=await onCreate({...form,role:'staff'});if(!r)throw Error('Could not create the account. Check the email and try again.');setSuccess({name:form.name,email:form.email});setForm({});setTab('staff')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function toggle(){setBusy(true);setError('');try{let r=await onToggle(confirm);if(!r)throw Error('Could not update access. Try again.');setConfirm(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
 let shown=accounts.filter(a=>a.role===(tab==='vendors'?'vendor':'staff'));
 return <><Summary items={[["Active staff",accounts.filter(a=>a.role==='staff'&&a.active).length],["Vendor accounts",accounts.filter(a=>a.role==='vendor').length],["Disabled accounts",accounts.filter(a=>!a.active).length]]}/><WorkspaceTabs value={tab} onChange={v=>{setTab(v);setError('')}} items={[['staff','Staff accounts'],['vendors','Vendor access'],['create','Create staff account']]}/>{error&&!confirm&&<p className="aw-error" role="alert">{error}</p>}{tab==='create'?<section className="aw-card"><h2>Create a staff account</h2><div className="aw-note"><ShieldCheck size={18}/>Staff can use POS, view stock and handle customer orders. Owner tools, supplier finances and settings stay restricted.</div><form className="aw-form" onSubmit={create}>{[['name','Staff name','text'],['email','Email address','email'],['password','Temporary password','password']].map(([key,label,type])=><label key={key}>{label}<input required type={type} minLength={key==='password'?6:undefined} autoComplete={key==='password'?'new-password':'off'} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<Button className="primary" disabled={busy}>{busy?'Creating…':'Create staff account'}</Button></form></section>:<RecordTable title={tab==='vendors'?'Vendor portal access':'Staff accounts'} columns={['Name','Email','Role / business','Access','Action']} rows={shown.map(a=><tr key={a.id}><td><strong>{a.name}</strong></td><td>{a.email}</td><td>{a.role==='vendor'?vendors.find(v=>v.id===a.vendor_id)?.name||'Vendor': 'Store staff'}</td><td><span className={'aw-status '+(!a.active?'pending':'')}>{a.active?'Active':'Disabled'}</span></td><td><Button variant="outline" onClick={()=>{setError('');setConfirm(a)}}>{a.active?'Disable access':'Enable access'}</Button></td></tr>)}/>}
 <AlertDialog open={Boolean(confirm)} onOpenChange={v=>{if(!v&&!busy)setConfirm(null)}}><AlertDialogContent className="aw-dialog"><AlertDialogTitle>{confirm?.active?'Disable':'Enable'} account access?</AlertDialogTitle><AlertDialogDescription>{confirm?.name} · {confirm?.email}. {confirm?.active?'They will no longer be able to use their portal. Their records stay intact.':'They can sign in again with their existing password.'}</AlertDialogDescription>{error&&<p className="aw-error">{error}</p>}<div className="aw-actions"><AlertDialogCancel disabled={busy}>Keep unchanged</AlertDialogCancel><Button className="primary" disabled={busy} onClick={toggle}>{busy?'Saving…':'Confirm access change'}</Button></div></AlertDialogContent></AlertDialog>
 <Dialog open={Boolean(success)} onOpenChange={v=>{if(!v)setSuccess(null)}}><DialogContent className="aw-dialog aw-success"><CheckCircle2 size={50}/><DialogTitle>Staff account created</DialogTitle><DialogDescription>{success?.name} can sign in at /staff using {success?.email} and the password you set. Share it privately. They can change it after signing in.</DialogDescription><Button className="primary" onClick={()=>setSuccess(null)}>Done</Button></DialogContent></Dialog></>
}
export function SectionSwitcher({items,children}){const [tab,setTab]=useState(items[0][0]);return <><WorkspaceTabs value={tab} onChange={setTab} items={items}/>{React.Children.toArray(children)[items.findIndex(x=>x[0]===tab)]}</>}
