import React,{useState} from 'react';
import {UserRound,ShoppingBag,ArrowRight,ShieldCheck,Eye,EyeOff,Store,Mail,LockKeyhole} from 'lucide-react';
import {auth,configured,GoogleAuthProvider,FacebookAuthProvider,signInWithPopup} from './firebase.js';
import './auth-pages.css';

async function request(path,payload,token){const res=await fetch('/api'+path,{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw Error(data.error||'Could not continue');return data}
function Header(){return <header className="auth-header"><a href="/shop" aria-label="Star Mart home"><img src="/logo.png" alt="Star Mart"/></a><nav><a href="/shop">Home</a><a href="/shop#products">Shop groceries</a><a href="/become-a-vendor">Become a vendor</a></nav><a className="auth-header-bag" href="/shop" aria-label="Go to store"><ShoppingBag size={20}/></a></header>}
function Field({icon:Icon,label,...props}){return <label className="sm-field"><span>{label}</span><span className="sm-input"><Icon size={18}/><input {...props}/></span></label>}
export function CustomerAuth({initialMode='signup'}){const [mode,setMode]=useState(initialMode),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e){e.preventDefault();setBusy(true);setError('');try{await request('/customer/'+(mode==='signup'?'signup':'login'),{name,email,password});location.href='/account'}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function social(provider){if(!configured){setError('Google/Facebook login needs Firebase configuration in Vercel. You can create an account with email now.');return}setBusy(true);setError('');try{const result=await signInWithPopup(auth,provider==='google.com'?new GoogleAuthProvider():new FacebookAuthProvider());await request('/customer/social',{provider},await result.user.getIdToken());location.href='/account'}catch(e){setError(e.code==='auth/account-exists-with-different-credential'?'This email is already linked to another sign-in method. Use the original method.':e.message?.replace(/^Firebase:\s*/,'')||'Social sign in failed')}finally{setBusy(false)}}
  return <div className="sm-auth"><Header/><main className="sm-auth-scene"><div className="sm-auth-copy"><span className="sm-eyebrow">STAR MART · HOUSE OF GROCERIES</span><h1>{mode==='signup'?<>Good groceries.<br/><em>Brighter days.</em></>:<>Your everyday shop,<br/><em>ready for you.</em></>}</h1><p>Everyday essentials, clear prices, and your shopping history in one place.</p><div className="sm-trust"><span>✦ Fresh essentials</span><span>✦ Simple shopping</span><span>✦ Star rewards</span></div></div><section className="sm-auth-card"><div className="sm-card-mark"><span className="sm-star">✦</span> CUSTOMER ACCOUNT</div><h2>{mode==='signup'?'Create your account':'Welcome back'}</h2><p>{mode==='signup'?'Join Star Mart and keep your groceries, bills and points together.':'Sign in to see your orders, bills and Star Points.'}</p><form onSubmit={submit}>{mode==='signup'&&<Field icon={UserRound} label="Full name" value={name} onChange={e=>setName(e.target.value)} autoComplete="name" required/>}<Field icon={Mail} label="Email address" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required/><label className="sm-field"><span>Password</span><span className="sm-input"><LockKeyhole size={18}/><input type={show?'text':'password'} minLength={mode==='signup'?8:1} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='signup'?'new-password':'current-password'} required/><button className="sm-eye" type="button" onClick={()=>setShow(!show)} aria-label={show?'Hide password':'Show password'}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>{error&&<p className="sm-error" role="alert">{error}</p>}<button className="sm-primary" disabled={busy}>{busy?'Please wait…':mode==='signup'?'Create account':'Sign in'}<ArrowRight size={17}/></button></form><div className="sm-divider"><span>or continue with</span></div><div className="sm-social"><button disabled={busy} onClick={()=>social('google.com')}><b className="sm-google">G</b> Google</button><button disabled={busy} onClick={()=>social('facebook.com')}><b className="sm-facebook">f</b> Facebook</button></div><p className="sm-switch">{mode==='signup'?'Already have an account?':'New to Star Mart?'} <button onClick={()=>{setMode(mode==='signup'?'login':'signup');setError('');history.replaceState(null,'',mode==='signup'?'/login':'/signup')}}>{mode==='signup'?'Sign in':'Create account'}</button></p></section></main></div>
}
export function VendorApply(){const [form,setForm]=useState({}),[error,setError]=useState(''),[done,setDone]=useState(false),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');try{await request('/vendor/apply',form);setDone(true)}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="sm-auth sm-vendor"><Header/><main className="sm-auth-scene"><div className="sm-auth-copy"><span className="sm-eyebrow">PARTNER WITH STAR MART</span><h1>Grow with your<br/><em>local grocery mart.</em></h1><p>Bring your products to Star Mart. Send your details and our team will review your application.</p><div className="sm-trust"><span>✦ Grocery partners</span><span>✦ Clear stock records</span></div></div><section className="sm-auth-card"><div className="sm-card-mark"><Store size={17}/> SUPPLIER PARTNERSHIP</div>{done?<><h2>Application received</h2><p>Star Mart will review your request. If approved, the owner will share your vendor login details.</p><a className="sm-primary" href="/shop">Back to store <ArrowRight size={17}/></a></>:<><h2>Become a vendor</h2><p>Apply to supply grocery products. The owner creates your account after approval.</p><form onSubmit={submit}><Field icon={Store} label="Business name" required value={form.business||''} onChange={e=>setForm({...form,business:e.target.value})}/><Field icon={UserRound} label="Contact person" required value={form.contact||''} onChange={e=>setForm({...form,contact:e.target.value})}/><Field icon={Mail} label="Email address" type="email" required value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/><Field icon={UserRound} label="Phone number" type="tel" required value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/>{error&&<p className="sm-error" role="alert">{error}</p>}<button className="sm-primary" disabled={busy}>{busy?'Sending…':'Apply as a vendor'}<ArrowRight size={17}/></button></form><p className="sm-switch">Already approved? <a href="/vendor">Vendor sign in</a></p></>}</section></main></div>}
