import React,{useEffect,useState} from 'react';
import {ShoppingBag,Wallet,Gift,CalendarDays,ArrowRight,ReceiptText,LogOut} from 'lucide-react';
import './customer-dashboard.css';
import {useLiveRefresh} from './live.js';

const money=n=>'Rs '+(Number(n||0)/100).toLocaleString('en-PK',{maximumFractionDigits:2});
const date=x=>new Date(x).toLocaleDateString('en-PK',{day:'numeric',month:'short',year:'numeric'});
export default function CustomerDashboard(){
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null);
  async function load(){
    try{const r=await fetch('/api/customer/overview',{credentials:'same-origin',cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error||'Could not load account');setData(j);setError('')}
    catch(e){setError(e.message)}finally{setLoading(false)}
  }
  useEffect(()=>{load()},[]);
  useLiveRefresh(load);
  async function logout(){await fetch('/api/customer/logout',{method:'POST',credentials:'same-origin'});location.href='/login'}
  const month=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit'}).format(new Date()),thisMonth=data?.monthly.find(x=>x.month===month),due=data?.bills.filter(x=>x.duePaisa>0)||[];
  return <div className="customer-app"><header><div className="customer-wrap customer-header"><a href="/shop"><img src="/logo.png" alt="Star Mart"/></a><nav><a href="/shop">Shop products</a><a href="/shop#products">Browse categories</a>{data&&<button onClick={logout}><LogOut size={16}/> Sign out</button>}</nav></div></header>
    {loading?<main className="customer-wrap customer-loading">Loading your dashboard…</main>:error?<main className="customer-wrap customer-empty"><h1>Welcome to Star Mart</h1><p>Sign in to view your purchases, credit balance and rewards.</p><a href="/signup">Create account or sign in <ArrowRight size={18}/></a><small>{error==='Please sign in'?'':error}</small></main>:<main className="customer-wrap">
      <section className="customer-hero"><div><span>MY STAR MART</span><h1>Hello, {data.customer.name.split(' ')[0]} 👋</h1><p>Your shopping, bills and rewards in one place.</p></div><a href="/shop#products">Continue shopping <ArrowRight size={18}/></a></section>
      <section className="customer-stats" aria-label="Account summary">
        <article><ShoppingBag/><span>Total shopping</span><strong>{money(data.summary.totalSpendPaisa)}</strong><small>{data.summary.billCount} completed counter bills</small></article>
        <article><CalendarDays/><span>This month</span><strong>{money(thisMonth?.totalPaisa)}</strong><small>{thisMonth?.bills||0} bills this month</small></article>
        <article className={data.summary.outstandingPaisa?'due':''}><Wallet/><span>Credit to pay</span><strong>{money(data.summary.outstandingPaisa)}</strong><small>{due.length} unpaid {due.length===1?'bill':'bills'}</small></article>
        <article className="points"><Gift/><span>Star Points</span><strong>{data.summary.points.toLocaleString('en-PK')}</strong><small>Available to redeem at the counter</small></article>
      </section>
      <div className="customer-columns"><section className="customer-card reward-card"><span className="eyebrow">YOUR REWARDS</span><h2>Make every grocery run count.</h2><p>Earn 1 point for each Rs 100 on a paid bill. On a later visit, redeem 100 points for Rs 50 off a counter bill of at least Rs 3,000.</p><div className="points-progress"><span style={{width:Math.min(100,Math.max(0,data.summary.points)%100)+'%'}}/></div><strong>{data.summary.points>=100?'Reward ready: ask the cashier to apply it.':(100-Math.max(0,data.summary.points)%100)+' points until your next reward'}</strong><small>Points on credit bills appear after full settlement. Rewards require recorded product costs, sufficient basket margin, and no other discount; one reward per bill. No cash exchange.</small></section>
      <section className="customer-card"><span className="eyebrow">CREDIT ACCOUNT</span><h2>What you still owe</h2>{due.length?due.map(b=><button className="due-row" key={b.id} onClick={()=>setSelected(selected===b.id?null:b.id)}><span><b>{b.id}</b><small>{date(b.createdAt)} · {b.items.length} items</small></span><strong>{money(b.duePaisa)}</strong></button>):<p className="muted">All bills are settled. You have no pending store credit.</p>}<small className="help">Payments are recorded by Star Mart staff and appear here after posting.</small></section></div>
      <section className="customer-card history"><div className="section-top"><div><span className="eyebrow">YOUR HISTORY</span><h2>Shopping bills</h2></div><ReceiptText/></div>{data.bills.length?data.bills.map(b=><article className="history-row" key={b.id}><button onClick={()=>setSelected(selected===b.id?null:b.id)} aria-expanded={selected===b.id}><span><b>{b.id}</b><small>{date(b.createdAt)} · {b.payment} · {b.items.length} items</small></span><span className="history-total"><b>{money(b.totalPaisa)}</b><small className={b.duePaisa?'unpaid':'paid'}>{b.duePaisa?'Due '+money(b.duePaisa):'Paid'}</small></span></button>{selected===b.id&&<div className="history-detail">{b.items.map((item,i)=><div key={i}><span>{item.name} × {item.qtyMilli/1000}</span><b>{money(item.totalPaisa)}</b></div>)}<div><span>Paid at checkout</span><b>{money(b.receivedPaisa)}</b></div>{b.paidLaterPaisa>0&&<div><span>Paid later</span><b>{money(b.paidLaterPaisa)}</b></div>}</div>}</article>):<p className="muted">No completed bills linked to your account yet. Ask the cashier to select your account at checkout.</p>}</section>
      <div className="customer-columns bottom"><section className="customer-card"><span className="eyebrow">MONTH BY MONTH</span><h2>Monthly shopping</h2>{data.monthly.length?data.monthly.slice(0,12).map(m=><div className="month-row" key={m.month}><span>{new Date(m.month+'-01').toLocaleDateString('en-PK',{month:'long',year:'numeric'})}</span><b>{money(m.totalPaisa)}</b></div>):<p className="muted">Monthly totals appear after your first completed bill.</p>}</section><section className="customer-card"><span className="eyebrow">ONLINE REQUESTS</span><h2>Orders</h2>{data.orders.length?data.orders.slice(0,12).map(o=><div className="month-row" key={o.id}><span>{o.id}<small>{date(o.created_at)} · {o.fulfillment} · {o.status}</small></span><b>{money(o.total_paisa)}</b></div>):<p className="muted">No online order requests yet.</p>}</section></div>
      <div className="customer-columns bottom"><section className="customer-card"><span className="eyebrow">PAYMENT RECORD</span><h2>Credit payments</h2>{data.payments.length?data.payments.slice(0,30).map(p=><div className="month-row" key={p.id}><span>{p.receipt_id}<small>{date(p.created_at)} · {p.method}</small></span><b>{money(p.amount_paisa)}</b></div>):<p className="muted">No credit settlements recorded yet.</p>}</section><section className="customer-card"><span className="eyebrow">POINTS RECORD</span><h2>Earned & redeemed</h2>{data.pointsHistory.length?data.pointsHistory.slice(0,30).map(p=><div className="month-row" key={p.id}><span>{p.kind==='earned'?'Earned on bill':'Redeemed at counter'}<small>{date(p.created_at)} · {p.receipt_id}</small></span><b className={Number(p.points)>0?'point-plus':'point-minus'}>{Number(p.points)>0?'+':''}{p.points} pts</b></div>):<p className="muted">Your first fully paid bill will start your points history.</p>}</section></div>
    </main>}
    <footer><div className="customer-wrap">Star Mart · House of Groceries <a href="/shop">Back to store →</a></div></footer>
  </div>
}
