import React,{useState} from 'react';
import {ArrowUpRight,ArrowRight,ScanBarcode,PackagePlus,Boxes,ShoppingBag,Wallet,AlertTriangle,Users,Clock3,ChevronRight,Activity,TrendingUp} from 'lucide-react';
import {Card,CardContent,CardHeader,CardTitle,CardDescription} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Tooltip,TooltipContent,TooltipProvider,TooltipTrigger} from '@/components/ui/tooltip';
import {pakistanDay} from './daily-sales.jsx';
const money=n=>'Rs '+(Number(n||0)/100).toLocaleString('en-PK',{maximumFractionDigits:0});
const compact=n=>Number(n||0).toLocaleString('en-PK',{maximumFractionDigits:2});
export default function PremiumDashboard({data,low,go,stock,orders=[],user}){
 const [period,setPeriod]=useState('7');const summary=data.dashboardSummary||{},todaySales=Number(data.todaySalesPaisa||0),pending=orders.filter(o=>o.status==='Pending'),inventory=data.products.reduce((n,p)=>n+Math.round(stock(p)*Number(p.cost_paisa)/1000),0);
 const days=Array.from({length:Number(period)},(_,i)=>{let d=new Date();d.setUTCDate(d.getUTCDate()-(Number(period)-1-i));let key=pakistanDay(d);let row=(data.receiptTrend||[]).find(x=>x.day===key);return {day:key,total:Number(row?.total_paisa||0),bills:Number(row?.bills||0)}}),sum=days.reduce((n,x)=>n+x.total,0),max=Math.max(...days.map(x=>x.total),1),hasSales=days.some(x=>x.total>0);
 const metrics=[{label:"Today's revenue",amount:money(todaySales),caption:'Completed bills · Pakistan time',Icon:Wallet,color:'green',go:'sales'},{label:'Total recorded sales',amount:money(summary.salesPaisa),caption:compact(summary.billCount)+' completed bills',Icon:ShoppingBag,color:'orange',go:'sales'},{label:'Inventory at cost',amount:money(inventory),caption:data.products.filter(p=>!p.deleted_at).length+' products in your catalog',Icon:Boxes,color:'mint',go:'products'},{label:'Orders to process',amount:String(pending.length),caption:money(pending.reduce((n,x)=>n+Number(x.total_paisa),0))+' awaiting completion',Icon:Clock3,color:'sand',go:'orders'}];
 const payments=data.paymentSummary||[],paymentTotal=payments.reduce((n,x)=>n+Number(x.total_paisa),0),colors=['#00745c','#fc2600','#00745c','#fc2600','#9a9a9a'];
 return <TooltipProvider><div className="sm-dash"><section className="pdash-hero"><div><Badge className="pdash-live"><span/> YOUR STORE, CONNECTED</Badge><h2>A better day.<br/><em>A smarter Star Mart.</em></h2><p>Welcome back, {user||'owner'}. Here’s what needs your attention today.</p><div className="pdash-hero-actions"><Button onClick={()=>go('pos')}><ScanBarcode size={17}/> Open counter</Button><Button variant="outline" onClick={()=>go('orders')}>Manage orders <ArrowUpRight size={16}/></Button></div></div><div className="pdash-orbit" aria-hidden="true"><div className="pdash-orbit-line"/><span className="pdash-orbit-top">HOUSE OF GROCERIES</span><div className="pdash-orbit-icon"><ShoppingBag size={66} strokeWidth={1}/><span>✦</span></div><span className="pdash-orbit-bottom">STOCK. SALES. SIMPLIFIED.</span></div><div className="pdash-today"><span>STORE SNAPSHOT</span><strong>{new Date().toLocaleDateString('en-PK',{timeZone:'Asia/Karachi',weekday:'long',day:'numeric',month:'long'})}</strong><small>{low.length?low.length+' items need a stock review':'Stock alerts are clear'}</small></div></section>
 <div className="pdash-kpis">{metrics.map(m=><Card className={'pdash-kpi '+m.color} key={m.label}><CardContent><div className="pdash-kpi-top"><span>{m.label}</span><span className="pdash-icon"><m.Icon size={18}/></span></div><strong>{m.amount}</strong><div className="pdash-kpi-bottom"><small>{m.caption}</small><Tooltip><TooltipTrigger asChild><Button variant="ghost" size="icon" aria-label={'View '+m.label} onClick={()=>go(m.go)}><ArrowUpRight size={17}/></Button></TooltipTrigger><TooltipContent>Open {m.go}</TooltipContent></Tooltip></div></CardContent></Card>)}</div>
 <div className="pdash-main-grid"><Card className="pdash-revenue"><CardHeader><div className="pdash-card-header"><div><CardDescription>PERFORMANCE</CardDescription><CardTitle>Revenue rhythm</CardTitle></div><Tabs value={period} onValueChange={setPeriod}><TabsList><TabsTrigger value="7">7 days</TabsTrigger><TabsTrigger value="30">30 days</TabsTrigger></TabsList></Tabs></div></CardHeader><CardContent><div className="pdash-chart-number"><strong>{money(sum)}</strong><span>Completed sales in this period</span></div><div className="pdash-chart" role="img" aria-label={'Revenue over '+period+' days: '+money(sum)}><div className="pdash-gridlines"><span>{money(max)}</span><span>{money(max/2)}</span><span>Rs 0</span></div><div className="pdash-bars">{days.map((d,i)=><Tooltip key={d.day}><TooltipTrigger asChild><div className="pdash-bar-column" tabIndex={0} aria-label={d.day+': '+money(d.total)}><div className="pdash-bar" style={{height:Math.max(d.total/max*140,d.total?6:2)+'px',opacity:i===days.length-1?1:.7}}/>{(period==='7'||i%5===0||i===days.length-1)&&<small>{d.day.slice(8)}/{d.day.slice(5,7)}</small>}</div></TooltipTrigger><TooltipContent>{d.day} · {money(d.total)} · {d.bills} bills</TooltipContent></Tooltip>)}</div>{!hasSales&&<div className="pdash-chart-empty">Your first completed sale starts the story.</div>}</div><div className="pdash-chart-footer"><span><i/> Completed receipts</span><Button variant="ghost" onClick={()=>go('sales')}>Explore sales <ArrowRight size={14}/></Button></div></CardContent></Card>
 <Card className="pdash-attention"><CardHeader><CardDescription>YOUR NEXT MOVE</CardDescription><CardTitle>Keep things moving.</CardTitle></CardHeader><CardContent><button className="pdash-task" onClick={()=>go('orders')}><span className="pdash-task-icon orange"><Clock3 size={20}/></span><span><b>Pending orders</b><small>{pending.length} waiting for your team</small></span><strong>{pending.length}</strong><ChevronRight size={15}/></button><button className="pdash-task" onClick={()=>go('products')}><span className="pdash-task-icon green"><AlertTriangle size={20}/></span><span><b>Stock watchlist</b><small>Check quantities before they run out</small></span><strong>{low.length}</strong><ChevronRight size={15}/></button><button className="pdash-task" onClick={()=>go('vendors')}><span className="pdash-task-icon sand"><Users size={20}/></span><span><b>Supplier network</b><small>{data.vendors.length} grocery partners</small></span><ChevronRight size={15}/></button><div className="pdash-note"><Activity size={20}/><div><b>Every action leaves a trail.</b><small>Follow product, stock and order changes in your activity log.</small><Button variant="link" onClick={()=>go('activity')}>View activity <ArrowUpRight size={13}/></Button></div></div></CardContent></Card></div>
 <div className="pdash-bottom-grid"><Card><CardHeader><div className="pdash-card-header"><div><CardDescription>RECENTLY COMPLETED</CardDescription><CardTitle>The latest at your counter</CardTitle></div><Button variant="ghost" size="sm" onClick={()=>go('sales')}>View all <ArrowUpRight size={15}/></Button></div></CardHeader><CardContent>{data.receipts.length?data.receipts.slice(0,5).map(r=><button className="pdash-receipt" key={r.id} onClick={()=>go('sales')}><span className="pdash-receipt-icon"><ShoppingBag size={17}/></span><span><b>{r.customer||'Walk-in customer'}</b><small>{r.id} · {new Date(r.created_at).toLocaleTimeString('en-PK',{timeZone:'Asia/Karachi',hour:'2-digit',minute:'2-digit'})}</small></span><Badge variant="secondary">{r.payment}</Badge><strong>{money(r.total_paisa)}</strong></button>):<div className="pdash-empty"><ShoppingBag size={28}/><b>Your next sale belongs here.</b><p>Finish a counter bill or fulfill a paid order to see its receipt.</p><Button variant="outline" onClick={()=>go('pos')}>Start a bill</Button></div>}</CardContent></Card><Card><CardHeader><CardDescription>PAYMENT MIX · ALL COMPLETED BILLS</CardDescription><CardTitle>How customers pay</CardTitle></CardHeader><CardContent><div className="pdash-payment-total"><strong>{money(paymentTotal)}</strong><span>Total recorded sales</span></div><div className="pdash-payment-track">{payments.map((p,i)=><span key={p.payment} style={{width:Number(p.total_paisa)/Math.max(paymentTotal,1)*100+'%',background:colors[i%colors.length]}}/>)}</div>{payments.length?payments.map((p,i)=><div className="pdash-payment-row" key={p.payment}><span><i style={{background:colors[i%colors.length]}}/>{p.payment}</span><b>{money(p.total_paisa)}</b></div>):<p className="pdash-muted">Payment breakdown appears after completed sales.</p>}<div className="pdash-mini-stats"><span><small>Recorded expenses</small><b>{money(summary.expensesPaisa)}</b></span><Button variant="ghost" size="sm" onClick={()=>go('expenses')}><ArrowUpRight size={17}/></Button></div></CardContent></Card></div>
 <div className="pdash-foot"><span><i/> Connected to your store records</span><span>Star Mart · Owner workspace</span></div></div></TooltipProvider>
}
