import React,{useEffect,useState} from 'react';
import {Boxes,ShoppingBag,Truck,Wallet,ClipboardList,LogOut,Plus,Upload,RefreshCw} from 'lucide-react';
import './vendor.css';
const rupees=n=>'Rs '+(Number(n||0)/100).toLocaleString('en-PK',{maximumFractionDigits:2});
const qty=n=>(Number(n||0)/1000).toLocaleString('en-PK',{maximumFractionDigits:3});
const when=v=>new Date(v).toLocaleString('en-PK',{dateStyle:'medium',timeStyle:'short'});
const categories=['Fruits','Vegetables','Dairy & Eggs','Bakery','Meat & Poultry','Fish & Seafood','Rice & Grains','Flour & Baking','Pulses & Lentils','Cooking Oil & Ghee','Spices & Condiments','Tea & Coffee','Beverages','Snacks & Sweets','Frozen Foods','Canned & Packaged','Personal Care','Household Cleaning','Baby Care','Pet Supplies','Other'];
async function request(path,method='GET',payload){let r=await fetch('/api'+path,{method,credentials:'same-origin',headers:payload?{'content-type':'application/json'}:{},body:payload?JSON.stringify(payload):undefined}),data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data}
const empty={name:'',sku:'',barcode:'',brand:'',category:'Fruits',packSize:'',unit:'piece',price:0,cost:0,reorder:5,reorderQty:10,description:''};
export default function VendorPanel({onLogout}){const [data,setData]=useState(null),[view,setView]=useState('overview'),[form,setForm]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');async function load(){try{setData(await request('/vendor/overview'));setError('')}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);const product=id=>data?.products.find(p=>p.id===id),purchases=data?.purchases||[],sales=data?.sales||[],payments=data?.payments||[],movements=data?.movements||[];const totalPurchase=purchases.reduce((n,p)=>n+Math.round(Number(p.qty_milli)*Number(p.unit_cost_paisa)/1000),0),atPurchase=purchases.reduce((n,p)=>n+(p.payment==='Paid'?Math.round(Number(p.qty_milli)*Number(p.unit_cost_paisa)/1000):Number(p.paid_paisa||0)),0),laterPaid=payments.reduce((n,p)=>n+Number(p.amount_paisa),0),balance=totalPurchase-atPurchase-laterPaid;
async function save(e){e.preventDefault();setBusy(true);setError('');try{let payload={...form},id=payload.id;delete payload.id;await request(id?'/products/'+id:'/products',id?'PUT':'POST',payload);setForm(null);await load();setNotice('Product saved. Store stock changes when the owner records a purchase.')}catch(e){setError(e.message)}finally{setBusy(false)}}
async function image(productId,file){if(!file)return;setBusy(true);try{let bitmap=await createImageBitmap(file),scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.82));let r=await fetch('/api/products/'+productId+'/image',{method:'POST',body:blob,credentials:'same-origin'}),j=await r.json();if(!r.ok)throw Error(j.error||'Image failed');await load();setNotice('Image uploaded.')}catch(e){setError(e.message)}finally{setBusy(false)}}
const nav=[['overview','Overview',Boxes],['products','My products',Boxes],['sales','Products sold',ShoppingBag],['purchases','Stock supplied',Truck],['payments','Cash & credit',Wallet],['movements','Stock history',ClipboardList]];
return <div className="vp"><aside className="vp-side"><a href="/shop"><img src="/logo.png" alt="Star Mart"/></a><div className="vp-label">VENDOR WORKSPACE</div><nav>{nav.map(([key,label,Icon])=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}><Icon size={18}/>{label}</button>)}</nav><div className="vp-bottom"><strong>{data?.vendor?.name||'Vendor'}</strong><span>Private supplier account</span><button onClick={onLogout}><LogOut size={17}/> Sign out</button></div></aside><main className="vp-main"><header><div><small>STAR MART / VENDOR</small><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div><button className="vp-outline" onClick={load}><RefreshCw size={16}/> Refresh</button></header>{error&&<p className="vp-error">{error}</p>}{notice&&<p className="vp-note">{notice}</p>}{!data?<p>Loading your vendor account…</p>:<>
{view==='overview'&&<><p className="vp-intro">Your products and every recorded stock transaction in one place.</p><div className="vp-metrics">{[['Products',data.products.length],['Units available',qty(data.products.reduce((n,p)=>n+Number(p.stock_milli),0))],['Units sold',qty(sales.reduce((n,s)=>n+Number(s.qty_milli),0))],['Amount owed by store',rupees(balance)]].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><div className="vp-card"><h2>Latest product sales</h2>{sales.slice(0,8).map(s=><div className="vp-line" key={s.id}><span>{product(s.product_id)?.name||'Product'} <small>{when(s.created_at)} · {s.receipt}</small></span><b>{qty(s.qty_milli)} sold · {rupees(s.line_total_paisa)}</b></div>)}{!sales.length&&<p>No sales recorded yet.</p>}</div></>}
{view==='products'&&<div className="vp-card"><div className="vp-head"><div><h2>My catalog</h2><p>Add products; the store owner receives stock before they become available to customers.</p></div><button className="vp-primary" onClick={()=>setForm({...empty})}><Plus size={17}/> Add product</button></div><div className="vp-table-wrap"><table><thead><tr><th>Product</th><th>Barcode / SKU</th><th>Category</th><th>Remaining</th><th>Cost / sell</th><th>Actions</th></tr></thead><tbody>{data.products.map(p=><tr key={p.id}><td><div className="vp-product">{p.image?<img src={p.image} alt=""/>:<span>★</span>}<div><b>{p.name}</b><small>{p.brand} · {p.pack_size||p.unit}</small></div></div></td><td>{p.barcode||p.sku||'—'}</td><td>{p.category||'—'}</td><td><b>{qty(p.stock_milli)} {p.unit}</b></td><td>{rupees(p.cost_paisa)} / {rupees(p.price_paisa)}</td><td><button onClick={()=>setForm({...p,cost:Number(p.cost_paisa)/100,price:Number(p.price_paisa)/100,reorder:Number(p.reorder_milli)/1000,reorderQty:Number(p.reorder_qty_milli)/1000,packSize:p.pack_size})}>Edit</button><label className="vp-upload"><Upload size={14}/> Image<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{image(p.id,e.target.files?.[0]);e.target.value=''}}/></label></td></tr>)}</tbody></table></div>{!data.products.length&&<p>No products yet. Add your first product.</p>}</div>}
{view==='sales'&&<div className="vp-card"><h2>Every recorded sale</h2><p>Sales are store customer transactions; they do not mean the store has paid your supplier invoices.</p><div className="vp-table-wrap"><table><thead><tr><th>Date / receipt</th><th>Product</th><th>Quantity</th><th>Selling amount</th><th>Store payment</th></tr></thead><tbody>{sales.map(s=><tr key={s.id}><td>{when(s.created_at)}<small>{s.receipt}</small></td><td>{product(s.product_id)?.name}</td><td>{qty(s.qty_milli)}</td><td>{rupees(s.line_total_paisa)}</td><td>{s.payment}</td></tr>)}</tbody></table></div></div>}
{view==='purchases'&&<div className="vp-card"><h2>Stock supplied to Star Mart</h2><p>These purchases are entered by the store owner after stock is received.</p><div className="vp-table-wrap"><table><thead><tr><th>Date / invoice</th><th>Product</th><th>Quantity</th><th>Batch / expiry</th><th>Total cost</th><th>Paid at receipt</th><th>Status</th></tr></thead><tbody>{purchases.map(p=><tr key={p.id}><td>{when(p.created_at)}<small>{p.invoice||'No invoice'}</small></td><td>{product(p.product_id)?.name}</td><td>{qty(p.qty_milli)}</td><td>{p.batch||'—'}<small>{p.expiry?String(p.expiry).slice(0,10):'No expiry'}</small></td><td>{rupees(Math.round(Number(p.qty_milli)*Number(p.unit_cost_paisa)/1000))}</td><td>{rupees(p.payment==='Paid'?Math.round(Number(p.qty_milli)*Number(p.unit_cost_paisa)/1000):p.paid_paisa)}</td><td>{p.payment}</td></tr>)}</tbody></table></div></div>}
{view==='payments'&&<><div className="vp-metrics">{[['Stock supplied',rupees(totalPurchase)],['Paid when received',rupees(atPurchase)],['Later payments',rupees(laterPaid)],['Outstanding credit',rupees(balance)]].map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><div className="vp-card"><h2>Later cash / bank payments</h2>{payments.map(p=><div className="vp-line" key={p.id}><span>{when(p.created_at)} · {p.method}<small>{p.reference||p.note||'Payment recorded by owner'}</small></span><b>{rupees(p.amount_paisa)}</b></div>)}{!payments.length&&<p>No later payments recorded yet.</p>}</div><p className="vp-foot">For older “Part paid” entries made before this ledger, the paid amount was not recorded; ask the owner to reconcile those entries.</p></>}
{view==='movements'&&<div className="vp-card"><h2>Every stock movement</h2><div className="vp-table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Type</th><th>Quantity change</th><th>Batch / expiry</th><th>Reason</th></tr></thead><tbody>{movements.map(m=><tr key={m.id}><td>{when(m.created_at)}</td><td>{product(m.product_id)?.name}</td><td>{m.kind}</td><td>{Number(m.qty_milli)>0?'+':''}{qty(m.qty_milli)}</td><td>{m.batch||'—'} {m.expiry?String(m.expiry).slice(0,10):''}</td><td>{m.reason}</td></tr>)}</tbody></table></div></div>}
</>}{form&&<div className="vp-overlay"><form className="vp-dialog" onSubmit={save}><div className="vp-head"><h2>{form.id?'Edit product':'Add product'}</h2><button type="button" onClick={()=>setForm(null)}>✕</button></div><div className="vp-fields">{[['name','Product name'],['sku','SKU'],['barcode','Barcode'],['brand','Brand'],['packSize','Pack size'],['unit','Unit'],['cost','Supplier cost (Rs)'],['price','Selling price (Rs)'],['reorder','Reorder level'],['reorderQty','Reorder quantity'],['description','Description']].map(([key,label])=><label key={key}>{label}<input required={key==='name'} type={['cost','price','reorder','reorderQty'].includes(key)?'number':'text'} min={['cost','price','reorder','reorderQty'].includes(key)?0:undefined} step={['cost','price'].includes(key)?'.01':key.startsWith('reorder')?'.001':undefined} value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Category<select value={form.category||'Fruits'} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><p>Adding a product does not add stock. Store owner records physical stock receipt.</p><button className="vp-primary" disabled={busy}>{busy?'Saving…':'Save product'}</button></form></div>}</main></div>}
